cron:
  process_due_reminder: "* 0-2 * * *"

publish_reminder:
  batch_size: 1000

ttl:
  five_minutes: 300
  fifteen_minutes: 900
  one_day: 86400

timeout:
  five_seconds: 5

channel:
  reminder:
    topic: "email"
    channel: "reminder"
    max_attempt: 5
    max_in_flight: 10
