cron:
  process_due_reminder: "* 0-2 * * *"

publish_reminder:
  batch_size: 1000

ttl:
  five_minutes: 300
  fifteen_minutes: 900
  one_day: 86400

timeout:
  five_seconds: 5

channel:
  exchange:
    reminder:
      name: "reminder.exchange"
      type: "direct"
  queue:
    reminder_send_email:
      exchange: "reminder.exchange"
      name: "reminder.send.email"
      routing_key: "reminder.email"
      consumer: "consumer.reminder.send.email"
